# Generated by Django 4.2.6 on 2023-10-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('titl2', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Хештег',
                'verbose_name_plural': 'Хештеги',
            },
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Коментарий', 'verbose_name_plural': 'Коментарии'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.CreateModel(
            name='PostTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, null=True)),
                ('image', models.ImageField(null=True, upload_to='media/')),
                ('description', models.TextField(null=True)),
                ('tipe_book', models.CharField(choices=[('Фантастика', 'Фантастика'), ('Художественная', 'Художественная'), ('Хоррор', 'Хоррор'), ('Фентези', 'Фентези')], max_length=100, null=True)),
                ('cost', models.PositiveIntegerField(null=True)),
                ('director', models.CharField(max_length=100, null=True)),
                ('number_of_page', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('hashtags', models.ManyToManyField(to='blog.hashtag')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
